### PR TITLE
Gui update (OLD/ROTTEN)

### PR DESCRIPTION
**Pull request by smerkousdavid**
I had some commit issues so I created a new branch. Description same as old one

### CODE REVIEW

**Comment by smerkousdavid** [comment]
Side note I kept the popup and standard commands that you guys had before. I just added a gui argument and a supposed to be private gui_format arg. Also if you guys want a better looking splash page you can do whatever you want to the splash.html. I just put something quickly together, I am not a front end guy as you can tell

screenshot_2016-09-05_21-22-12

screenshot_2016-09-05_21-24-23

screenshot_2016-09-05_21-24-43

**Comment by reynhout** [comment]
@smerkousdavid Would you mind making a single PR with _only_ the new/modified files in the changeset? We like to keep the history clean -- and also these changesets are too large to view on GitHub. Thanks!

**Comment by smerkousdavid** [comment]
@reynhout If I understand you correctly. Do you want me to keep the path relativity and delete _everything not changed_?

**Comment by reynhout** [comment]
@smerkousdavid The diff should include only files added or modified (not the `zenity` binary, and not the `src` tree). I think that will end up being three or four files instead of the 250+ in the original diff (and then removing 250+ in the second diff).

**Comment by smerkousdavid** [comment]
@reynhout That was much more clear thanks,

**Pull request closed without merging**
