### PR TITLE
Added Python 3 GTK gui for updating

### PR DESCRIPTION
**Pull request by AlexApps99**
image
image
image
image

### CODE REVIEW

**Comment by AlexApps99** [comment]
@reynhout 
I've been working on a GUI for a few days, wondering what you think of it.
Some info:
Uses Python 3, GTK 3, Aptdaemon etc
AFAIK all dependencies come preinstalled and should work out of the box - haven't tested on a fresh install yet though.

You can run it with the arguments `--help` `-h`, `--version` `-v`, `--debug` `-d`.
This script needs root, and checks for it before running. (Should be setup in .desktop to just work)
If you have any questions please contact me, I'm open for new ideas.
This is my first application of this kind, please tell me if you find any bugs and I will try to fix them.
Thanks :+1:

**Comment by AlexApps99** [comment]
Any feedback on this?

**Comment by msangel** [comment]
Shouldn't the "update" do the both "package list update" and then "upgrade packages" in sequence? As a final user these two buttons makes me confusing. I just want to get updates.

P.s.: I'm **not** a maintainer of this project.

**Comment by AlexApps99** [comment]
I'll keep that in mind as I improve this, thanks for the feedback!

**Comment by dvdmuckle** [comment]
This looks really nice! Just one concern, how many new dependencies does this add? Concerning the use of Python GTK elsewhere, I'm betting it's not that bad.

**Comment by AlexApps99** [comment]
I'm not sure, but I didn't need to install anything to get it working.
Not sure if I installed anything in the past, if anybody can test that would be nice.

**Comment by reynhout** [comment]
@AlexApps99 Hi, this looks great! I agree with @msangel that a single step would easier to understand for most users.

The "checking for updates" step could be run immediately on launch. Then when complete, the "upgradable" list could be displayed (preferably in the same window, as a scrollable list -- it might be long!) and the user could make an informed choice about whether to upgrade or not.

The flip side is that the full list can be overwhelming to some users. We show it presently, because hiding it is usually worse. Other distros get around the problem by adding a "Show details" disclosure, which works well.

Thanks for putting this together. We'd love to include something like this with GalliumOS!

**Comment by AlexApps99** [comment]
I've combined both actions into one button, is there anything else that I should do?
I feel like running update as soon as the application's opened is dangerous because the user may not want to update, but instead view the program to discover what it's purpose is etc. so instead I have placed a single button clearly labeled so users understand what the program does and how to use it without starting it accidentally.
image
If you would prefer it running on startup instead, I can do that too, I'm just asking for your opinion on this.
Thanks, keep up the good work on GalliumOS!

**Comment by AlexApps99** [comment]
Is anybody willing to test this?
Before this is accepted it should be tested on someone else's computer.
Thanks
Edit: Preferably with a different GTK theme and icon theme to test compatibility

**Comment by AlexApps99** [comment]
image
image
image
Can confirm, works with different icons and themes.

**Comment by AlexApps99** [comment]
Has anybody else tried it yet?
Thanks

**Comment by AlexApps99** [comment]
@reynhout Is this ok?

**Comment by reynhout** [comment]
@AlexApps99 Hey, sorry for the delay on this PR!

We're in pre-3.0 code freeze, so only critical bugfixes are merge candidates right now. Our normal process for big changes is on hold for just a bit longer.

Here are my personal thoughts so far (other reviewers, please share yours!):

* Removing the "update only" is good for simplicity, but the UI obviously suffers with just one button. I'm no GUI designer, but I think the button should be normal-sized, and the usual two buttons would be reasonable: "Cancel" and "Update"?
* We use "Update" for "update packages". And the menu item is "GalliumOS Update", so the "yes, do all the things" option should be called "Update". I know this conflicts with APT's naming, but APT's naming is confusing.
* I don't think we should pop a new window to display output from the APT commands. It is distracting and jumpy. A textarea inside the primary window seems preferable.
* I'm hesitant to ask people to "Update" without telling what they will be updating. Maybe open the window with "Checking for updates..." in the textarea while APT::Update is working, then display the pkg list and enable the "Update" button?
* The icon in the window is inconsistent across the screenshots -- is this a consequence of different GTK themes? That's fine I guess, as long as the icon matches in the default theme, which is the only one we really care about. Maybe we should replace with a GalliumOS logo though?

Just thoughts.. Anyone else?

**Comment by AlexApps99** [comment]
- That's a good point, I'll add a cancel/quit button soon
- Ok, Update it is
- I'm not sure if there is a way to embed information in a textarea without implementing in another way, popups are the only option for aptdaemon
- I could do that but I'm not sure if it should update without any user approval/input
- It is due to GTK icon themes, I could replace it with GalliumOS logo if you prefer

**Comment by reynhout** [comment]
Oh, also: running `galliumos-update` from a shell should always launch a text version. This can/should be the same code as the GUI version, no need to keep the old Bourne shell script. The launcher menu should run the GUI of course.

**Comment by AlexApps99** [comment]
Ok

**Comment by reynhout** [comment]
> I'm not sure if there is a way to embed information in a textarea without implementing in another way, popups are the only option for aptdaemon

Ah, not sure what the limitations are there. I know you can call APT commands through python that return dicts, but only because I've seen code elsewhere that does it. :)

**Comment by ghost** [comment]
I'd just like to add my $0.02 here.

I am downloading your repo on my computer to test out right now. This looks really cool but I think it is important to remember the reasons we decided against allowing Canonical's (also Python GTK based) updater to be included, the main one being that it is very bulky and takes up a lot of RAM. Since this is still using the old shell script for the background notifier and we don't expect people to keep the application itself open for a long time, I'm sure it won't be a problem here, plus your application looks a hell of a lot lighter than Canonical's, but I think it's worth noting at any rate.

All that being said, it really does look good, so as long as a little extensive testing shows that these are not problems, I'd like to get this on the short list for 3.1 priorities.

**Comment by AlexApps99** [comment]
It has now been exactly one year since the last activity on this PR (quite a coincidence I checked today in particular), it's safe to assume that this definitely isn't getting merged.

Thanks anyways, this OS was a lot of help when I only had a Chromebook :)

**Pull request closed without merging**
