### PR TITLE
GUI zenity update script

### PR DESCRIPTION
**Pull request by smerkousdavid**
Added zenity to bin, added gksudo for non terminal password support just a cleaner look in general

### CODE REVIEW

**Comment by smerkousdavid** [comment]
One note nothing has been added to the debian section since i've added splash.html in /usr/share/gallium/

**Comment by reynhout** [comment]
@smerkousdavid Thanks for the PR!

Looking it over, I think we could remove the  entire `src` tree from the patch, and configure the `galliumos-update` pkg to depend on the `zenity` pkg (which would then be fetched from the Canonical repositories). Is that correct?

**Comment by smerkousdavid** [comment]
@reynhout Yeah that would work. I'm pretty sure the ppa is defaulted in all newer debians, so it would work. Zenity isn't that large, besides its depends such as gtk2. So I included the executable in the usr/bin so I think we don't even need to add the Canonical repo.

**Comment by reynhout** [comment]
`zenity` is already included in the default install of GalliumOS, in fact.

**Comment by smerkousdavid** [comment]
@reynhout Oops, dumb mistake of mine. I should have tested to see if it was... I compiled from source.

**Comment by reynhout** [comment]
@smerkousdavid It's OK, I didn't know either, until I looked a moment ago. :)

Would you mind resubmitting your PR with only the necessary files? That will make it easier to review.

Thanks again!

**Comment by smerkousdavid** [comment]
@reynhout No problem should I remove the /src in the PR?

**Comment by reynhout** [comment]
@smerkousdavid Thanks. Yes, the `src` dir and `usr/bin/zenity`. I think that's all.

**Pull request closed without merging**
