### PR TITLE
Gui update

### PR DESCRIPTION
**Pull request by smerkousdavid**
Hopefully the history is cleaner now

### CODE REVIEW

**Comment by smerkousdavid** [comment]
@reynhout Sorry for all this hassle... Second time I'm doing a PR

**Comment by reynhout** [comment]
@smerkousdavid Awesome, thank you. The PR process can be confusing. The new diff is much more readable. There are a couple of stray files there still, not sure how that happened (maybe you weren't all the way back to the origin changeset?). But we can review it in GitHub now, and that helps a lot.

**Comment by smerkousdavid** [comment]
@reynhout I know the makefile and the original c file i deleted weren't from the original because there is no way of commiting them without the changes. Also I wiped my repo and practically reforked it and copied the modified ones from my old repo. So there shouldn't be any stray files... That's weird

**Comment by reynhout** [comment]
@smerkousdavid Oh, you're quite right. I didn't look at them carefully. I wrote those files. They actually do need to be included in the repo, and not removed by your patch. :)

**Comment by smerkousdavid** [comment]
@reynhout From what I'm hearing it's another round I guess

**Comment by reynhout** [comment]
@smerkousdavid you should be able to amend your patches. You don't need to recreate the whole PR process. And we can squash the changesets on merge as well. But from a quick review, there are a few more things to take care of before we would be able to merge anyway, so don't go to the effort of cleaning up what's there quite yet.

I (and probably others) will add more comments to this thread, but likely not til tomorrow or so.

**Comment by smerkousdavid** [comment]
@reynhout  Okay I am probably done for today anyways. I'll probably be at school tomorrow until 6pm central time. So any comments or bashing about my code won't get a response till then unless i'm free. Bye

**Comment by smerkousdavid** [comment]
I found that gnome-screensaver works so far an amzing replacement for xscreensaver as of reading on issue 153. I haven't tried VT2 yet but I can

**Comment by reynhout** [comment]
@smerkousdavid nothing major, just a few issues I noticed on a quick read. Typos and messaging improvements mostly.

I haven't tested your code yet. One thing to keep in mind is that users must be presented with the full output from the dist-upgrade command so they can make decisions about packages upgraded. Also, there are warnings (e.g. downgrades) and other semi-error (and full-fledged error) error that need to be displayed in full. Sometimes the output can be very large.

If I remember correctly, there are also some conditions where there is more than one prompt for confirmation, or where more than two (Y/N) possibilities exist for input.

The full output also needs to be selectable and copyable into the clipboard. This is probably not an issue, just want to make sure not to forget about it when testing.

**Comment by smerkousdavid** [comment]
@reynhout Okay sure I can probably work on having a logging part. Do you want me to also have the update write to a temporary log. So if something fails they could push that report? That won't be too hard I'll just have to add a tee.

Also it seems as if your GTK+ theme is broken/missing some images

/usr/share/themes/Arc-Dark-GalliumOS/gtk-2.0/main.rc:915: Unable to locate image file in pixmap_path: "assets/focus-line-button.png"
/usr/share/themes/Arc-Dark-GalliumOS/gtk-2.0/main.rc:918: Background image options specified without filename

**Comment by smerkousdavid** [comment]
@reynhout I think it might be a little bit difficult to have the updating text... Is it okay to after an after script  view/progress view, over a realtime? Also do you still want me to save it to a temporary file?

**Comment by smerkousdavid** [comment]
@reynhout Changes have been made... I'm busy so you guys can do whatever you want with the script if you even want it I don't really care. Sorry I have a big project coming up that I need to do.

**Comment by reynhout** [comment]
@smerkousdavid Sorry, still catching up from yesterday.

I don't think a log file will work. We need to display the messages in realtime (and probably interactively) to the user to prevent the "assumption of correctness" in warning/error situations. This makes for a more complicated GUI implementation, which is why we chose the terminal version for rev 1.

BTW, APT keeps a log in `/var/log/apt` of actions that it performs. We use that occasionally when a user has gotten unexpected results. It does not log anything if it doesn't do anything though, so we rely on copy/pasted text in those situations (which is why the copyability is also essential, but again probably true by default).

I think in order to get full messaging and interactivity, we'd need to use something like Python and the Tk libraries (TkInter or similar?). And we'd need to check the apt code for the full set of conditions to handle on the UI side (or just dump it all into an interactive window...but that would bring us back to a slightly prettier version of the existing text interface, so might not be worthwhile).

Do you have any other ideas for how to get there?

Thanks for your thoughts and efforts!

**Comment by smerkousdavid** [comment]
@reynhout I got the somewhat interactive working. It now updates the text realtime (It took a bit of doing), now it has a notification part where it will show you any new errors that pop up. Also it give you now a list of packages that need to be updated. The only thing I don't have is it "interactive console" where you can input into the text box. Also I wouldn't recommend Tkinter even though it was built off of gtk it was made for overly simplistic designs. Also yeah I agree with you spending that much time on little benefit won't be worth it

**Comment by smerkousdavid** [comment]
@reynhout If for some reason gtk crashes (zenity), the update will still run in the background. I "assume" yes after the first page where they have the option to see all the available updates

**Pull request closed without merging**
